---
- hosts: local
  user: jhillix
  vars:
    home: "/home/jhillix"
  roles:
#   - base
   - update-cache
   - network-interfaces
   - user
   - sudo
   - desktop-environment
   - wifi
   - terminal
   - intellij
