---
- name: Install display server (X.Org) bits
  pacman:
    name: [xorg-server, xorg-apps, xorg-xinit]
    state: present
  become: yes

# Check for the correct graphics driver for your system and update here if needed
# Ex. lspci | grep -i --color 'vga\|3d\|2d'
- name: Install graphics driver
  pacman:
    name: xf86-video-intel
    state: present
  become: yes

- name: Install display manager
  pacman:
    name: lxdm
    state: present
  become: yes

- name: Install desktop environment (Cinnamon)
  pacman:
    name: cinnamon
    state: present
  become: yes
  notify:
  - enable lxdm

- name: Install networkmanager
  pacman:
    name: networkmanager
    state: present
  become: yes
  notify:
  - enable NetworkManager

- name: Install gnome-keyring
  pacman:
    name: gnome-keyring
    state: present
  become: yes

- name: Install blueberry (to add Bluetooth support)
  pacman:
    name: blueberry
    state: present
  become: yes

- name: Install Cinnamon themes and icons
  aur:
    name:
      - mint-y-icons
      - mint-x-icons
      - mint-themes
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: aur_builder

# TODO: Broken - but running manually works
#- name: Install Cinnamon sound events
#  aur:
#    name:
#      - cinnamon-sound-effects
#      - mint-sounds
#    use: makepkg
#    skip_installed: yes
#  become: yes
#  become_user: aur_builder

- name: Install Google Noto Mono Regular
  pacman:
    name: noto-fonts
    state: present
  become: yes

- name: Install gnome-screenshot
  pacman:
    name: gnome-screenshot
    state: present
  become: yes

- name: Create 'workspace' directory
  file:
    path: /home/jhillix/workspace
    state: directory
