---
- name: Install display server (X.Org) bits
  pacman:
    name: [xorg-server, xorg-apps, xorg-xinit]
    state: present

#- name: Install graphics driver
# Check for the correct graphics driver for your system and update here if needed

#- name: Install display manager