---
- name: Install display server (X.Org) bits
  pacman:
    name: [xorg-server, xorg-apps, xorg-xinit]
    state: present

# Check for the correct graphics driver for your system and update here if needed
# Ex. lspci | grep -i --color 'vga\|3d\|2d'
- name: Install graphics driver
  pacman:
    name: xf86-video-intel
    state: present

- name: Install display manager
  pacman:
    name: lxdm
    state: present

- name: Install desktop environment (Cinnamon)
  pacman:
    name: cinnamon
    state: present
  notify:
  - enable lxdm

- name: Install networkmanager
  pacman:
    name: networkmanager
    state: present
  notify:
  - enable NetworkManager

- name: Install gnome-keyring
  pacman:
    name: gnome-keyring
    state: present

- name: Install blueberry (to add Bluetooth support)
  pacman:
    name: blueberry
    state: present

# - name: Install Cinnamon themes and icons
#   pacman:
#     name: blueberry
#     state: present

# - name: Install Cinnamon sound events
#   pacman:
#     name: blueberry
#     state: present

# - name: Install gnome-screenshot
#   pacman:
#     name: gnome-screenshot
#     state: present
