---
- name: Install ulauncher
  aur:
    name: ulauncher
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: aur_builder

- name: Install mailspring
  aur:
    name: mailspring
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: aur_builder

- name: Install saleae-logic (High speed USB logic analyzer)
  aur:
    name: saleae-logic
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: aur_builder

- name: Install sigrok-cli (Client software that supports various hardware logic analyzers, CLI client)
  aur:
    name: sigrok-cli
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: aur_builder