---
- name: Install ulauncher
  aur:
    name: ulauncher
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: aur_builder

- name: Install mailspring
  aur:
    name: mailspring
    use: makepkg
    skip_installed: yes
  become: yes
  become_user: aur_builder