---
- name: enable lxdm
  systemd:
    name: lxdm
    enabled: yes

- name: enable NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes

# This will only run when its attached task runs due to a change
- name: xdg-user-dirs-update
  shell: >
    xdg-user-dirs-update
  args:
    executable: /bin/bash
